In [39]:
import numpy as np

In [40]:
np.__version__

'2.4.4'

## Create & Read

#### 1D Array

In [10]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [12]:
arr1.shape

(6,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [11]:
arr1.size

6

#### 2D Array

In [13]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape # (row, col)

(2, 3)

In [16]:
arr2.dtype

dtype('int64')

#### 3D Array

In [43]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [44]:
arr3.ndim

3

In [22]:
arr3.shape # (layers, columns, rows)

(3, 2, 3)

In [45]:
arr3.size

18

### Create random array

In [25]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.5559586 , 0.26634422, 0.55943181],
        [0.85279814, 0.45303435, 0.8610396 ]],

       [[0.42716768, 0.74161701, 0.26392051],
        [0.40154195, 0.09754656, 0.9186238 ]],

       [[0.6796113 , 0.80838172, 0.36508801],
        [0.90348918, 0.72997086, 0.69671208]]])

In [26]:
randomArr.dtype

dtype('float64')

In [29]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
zeroes.ndim

3

In [33]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [34]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
arr3[0][0][2]

np.int64(5)

In [46]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [51]:
arr3[1][0][1]

np.int64(5)

In [52]:
arr3[1, 0, 1]

np.int64(5)

In [54]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [55]:
a1

array([[[0.12118322, 0.82639467],
        [0.13614371, 0.27650951],
        [0.76454775, 0.77616043]],

       [[0.95563341, 0.47010727],
        [0.01722738, 0.6019926 ],
        [0.38989107, 0.83758236]]])

In [56]:
a2

array([[[0.49022488, 0.91469253],
        [0.44730801, 0.25214771],
        [0.7883222 , 0.46069149]],

       [[0.38987284, 0.00410019],
        [0.02289094, 0.97177396],
        [0.37101191, 0.23725211]]])

#### Basic Math Operations

In [57]:
np.add(a1, a2)

array([[[0.6114081 , 1.7410872 ],
        [0.58345171, 0.52865722],
        [1.55286995, 1.23685193]],

       [[1.34550625, 0.47420746],
        [0.04011832, 1.57376656],
        [0.76090297, 1.07483447]]])

In [58]:
np.subtract(a1, a2)

array([[[-0.36904166, -0.08829785],
        [-0.3111643 ,  0.02436181],
        [-0.02377444,  0.31546894]],

       [[ 0.56576057,  0.46600709],
        [-0.00566357, -0.36978137],
        [ 0.01887916,  0.60033025]]])

In [59]:
np.divide(a1, a2)

array([[[  0.24719924,   0.90346717],
        [  0.30436233,   1.09661721],
        [  0.96984172,   1.68477265]],

       [[  2.45114126, 114.65507086],
        [  0.7525849 ,   0.61947801],
        [  1.0508856 ,   3.53034733]]])

In [60]:
np.multiply(a1, a2)

array([[[5.94070292e-02, 7.55897030e-01],
        [6.08981702e-02, 6.97212397e-02],
        [6.02709964e-01, 3.57570509e-01]],

       [[3.72575513e-01, 1.92752790e-03],
        [3.94350921e-04, 5.85000729e-01],
        [1.44654228e-01, 1.98718184e-01]]])

#### Statistical operations

In [61]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [62]:
sqrt

np.float64(5.0)

In [63]:
abs

np.int64(2)

In [64]:
power

np.int64(256)

In [65]:
log

np.float64(3.2188758248682006)

In [66]:
mins

np.float64(0.017227377824073797)

In [67]:
maxs

np.float64(0.9717739612891073)

#### Update

In [68]:
arr3[0, 0, 2] = 500

In [69]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [70]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [71]:
# Reshape
arr3.shape

(3, 2, 3)

In [75]:
arr3_reshape = arr3.reshape((2, 3, -1))

In [76]:
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [77]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [78]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [83]:
# Insert

In [84]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [85]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [87]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [88]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.76850861, 0.41053033, 0.10031439],
        [0.84890717, 0.73193854, 0.81896314]],

       [[0.56435956, 0.3614747 , 0.52863547],
        [0.07664133, 0.33093486, 0.97921703]],

       [[0.78745369, 0.39671004, 0.79138102],
        [0.51617865, 0.44933054, 0.97190342]]])

In [90]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [91]:
arr5

array([[[0.84890717, 0.73193854, 0.81896314]],

       [[0.07664133, 0.33093486, 0.97921703]],

       [[0.51617865, 0.44933054, 0.97190342]]])

In [92]:
np.save("new_array", arr5)

In [93]:
np.load("new_array.npy")

array([[[0.84890717, 0.73193854, 0.81896314]],

       [[0.07664133, 0.33093486, 0.97921703]],

       [[0.51617865, 0.44933054, 0.97190342]]])